spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?user=postgres.ryudffosphmreihtkjew&password=${DB_PASS}&preferQueryMode=simple
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRES_IN:7200000}
spring.security.user.name=admin
spring.security.user.password=123456

payos.client-id=${PAYOS_CLIENT_ID:}
payos.api-key=${PAYOS_API_KEY:}
payos.checksum-key=${PAYOS_CHECKSUM_KEY:}
payos.base-url=${PAYOS_BASE_URL:https://api-merchant.payos.vn}
app.frontend-base-url=${FRONTEND_BASE_URL:http://localhost:5173}
